# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/formCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Controller.CardController import CardController

class Ui_MainWindow(object):

    def __init__(self):
        self.cardController = CardController()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 329)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.editId = QtWidgets.QLineEdit(self.centralwidget)
        self.editId.setGeometry(QtCore.QRect(130, 10, 61, 20))
        self.editId.setObjectName("editId")
        self.editDescricao = QtWidgets.QLineEdit(self.centralwidget)
        self.editDescricao.setGeometry(QtCore.QRect(130, 40, 301, 20))
        self.editDescricao.setObjectName("editDescricao")
        self.editNome = QtWidgets.QLineEdit(self.centralwidget)
        self.editNome.setGeometry(QtCore.QRect(130, 70, 231, 21))
        self.editNome.setObjectName("editNome")
        self.editForca = QtWidgets.QLineEdit(self.centralwidget)
        self.editForca.setGeometry(QtCore.QRect(130, 100, 61, 20))
        self.editForca.setObjectName("editForca")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizar.setGeometry(QtCore.QRect(220, 200, 75, 23))
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.btnExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.btnExcluir.setGeometry(QtCore.QRect(300, 200, 75, 23))
        self.btnExcluir.setObjectName("btnExcluir")
        self.btnConsultar = QtWidgets.QPushButton(self.centralwidget)
        self.btnConsultar.setGeometry(QtCore.QRect(50, 200, 75, 23))
        self.btnConsultar.setObjectName("btnConsultar")
        self.editMagia = QtWidgets.QLineEdit(self.centralwidget)
        self.editMagia.setGeometry(QtCore.QRect(130, 130, 61, 20))
        self.editMagia.setText("")
        self.editMagia.setObjectName("editMagia")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.editFogo = QtWidgets.QLineEdit(self.centralwidget)
        self.editFogo.setGeometry(QtCore.QRect(130, 160, 61, 20))
        self.editFogo.setText("")
        self.editFogo.setObjectName("editFogo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 160, 47, 13))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnConsultar.clicked.connect(self.consultar)
        self.btnCadastrar.clicked.connect(self.cadastrar)
        self.btnAtualizar.clicked.connect(self.atualizar)
        self.btnAtualizar.setEnabled(False)
        self.btnExcluir.clicked.connect(self.excluir)

    def consultar(self):
        dados = self.cardController.consultar(int(self.editId.text()))
        if dados:
            self.editDescricao.setText(dados[1])
            self.editNome.setText(dados[2])
            self.editForca.setText(dados[3])
            self.editMagia.setText(dados[4])
            self.editFogo.setText(dados[5])
            self.btnCadastrar.setEnabled(False)
            self.btnAtualizar.setEnabled(True)
            self.editNome.setEnabled(False)
            self.editDescricao.setEnabled(False)
            print("Consultado valores!")
        else:
            self.editDescricao.setText('')
            self.editNome.setText('')
            self.editForca.setText('')
            self.editMagia.setText('')
            self.editFogo.setText('')
            self.editNome.setEnabled(True)
            self.editDescricao.setEnabled(True)
            self.btnCadastrar.setEnabled(True)
            print("Não foi possivel consultar!")

    def cadastrar(self):
        if self.cardController.cadastrar(self.editId.text(),
                                         self.editDescricao.text(),
                                         self.editNome.text(),
                                         int(self.editForca.text()),
                                         int(self.editMagia.text()),
                                         int(self.editFogo.text())):
            print('Card cadastrado!')

            self.editId.setText('')
            self.editDescricao.setText('')
            self.editNome.setText('')
            self.editForca.setText('')
            self.editMagia.setText('')
            self.editFogo.setText('')

        else:
            self.editId.setText('')
            print('Erro ao cadastrar Card!')

    def atualizar(self):
        if self.cardController.atualizar(self.editId.text(),
                                         int(self.editForca.text()),
                                         int(self.editMagia.text()),
                                         int(self.editFogo.text())):
            print('Card atualizado!')

            self.editId.setText('')
            self.editDescricao.setText('')
            self.editNome.setText('')
            self.editForca.setText('')
            self.editMagia.setText('')
            self.editFogo.setText('')
            self.editNome.setEnabled(True)
            self.editDescricao.setEnabled(True)
            self.btnCadastrar.setEnabled(True)
        else:
            print('Erro ao atualizar Card!')

    def excluir(self):
        if self.cardController.excluir(self.editId.text()):
            print('Card excluído!')
            self.editId.setText('')
            self.editDescricao.setText('')
            self.editNome.setText('')
            self.editForca.setText('')
            self.editMagia.setText('')
            self.editFogo.setText('')
            self.editNome.setEnabled(True)
            self.editDescricao.setEnabled(True)
            self.btnCadastrar.setEnabled(True)
        else:
            print('Erro ao excluir Card!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Código"))
        self.label_2.setText(_translate("MainWindow", "Descrição"))
        self.label_3.setText(_translate("MainWindow", "Nome"))
        self.label_4.setText(_translate("MainWindow", "Força"))
        self.btnCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.btnAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.btnExcluir.setText(_translate("MainWindow", "Excluir"))
        self.btnConsultar.setText(_translate("MainWindow", "Consultar"))
        self.label_5.setText(_translate("MainWindow", "Magia"))
        self.label_6.setText(_translate("MainWindow", "Fogo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
